package passwordsaver.progettotwebpasswordsaver.constants;

public class Apis {
    public static final String LOGIN = "/login";
    public static final String SIGNUP = "/signup";
    public static final String PASSWORDS = "/passwords";
    public static final String PASSWORDS_GETPASSWORD = PASSWORDS + "/getpassword";
    public static final String PASSWORDS_GETDETAILEDPASSWORD = PASSWORDS + "/getdetailedpassword";
    public static final String PASSWORDS_GETDECODEDPASSWORD = PASSWORDS + "/getdecodedpassword";
    public static final String PASSWORDS_GETDETAILEDPASSWORDS = PASSWORDS + "/getdetailedpasswords";
    public static final String PASSWORDS_GETDETAILEDPASSWORDSBYSERVICE = PASSWORDS + "/getdetailedpasswordsbyservice";
    public static final String PASSWORDS_GETDETAILEDDELETEDPASSWORDSBYUSER = PASSWORDS + "/getdetaileddeletedpasswordsbyuser";
    public static final String PASSWORDS_GETSTARREDPASSWORDS = PASSWORDS + "/getstarredpasswords";
    public static final String PASSWORDS_GETDETAILEDSTARREDPASSWORDS = PASSWORDS + "/getdetailedstarredpasswords";
    public static final String PASSWORDS_ADDPASSWORD = PASSWORDS + "/addpassword";
    public static final String PASSWORDS_UPDATEPASSWORD = PASSWORDS + "/updatepassword";
    public static final String PASSWORDS_RECOVERPASSWORD = PASSWORDS + "/recoverpassword";
    public static final String PASSWORDS_DELETEPASSWORD = PASSWORDS + "/deletepassword";
    public static final String USERS = "/users";
    public static final String USERS_GETDETAILEDUSERS = USERS + "/getdetailedusers";
    public static final String USERS_GETDETAILEDUSERSBYUSERTYPE = USERS + "/getdetailedusersbyusertype";
    public static final String USERS_GETUSER = USERS + "/getuser";
    public static final String USERS_GETDETAILEDUSER = USERS + "/getdetaileduser";
    public static final String USERS_GETUSERTYPEOFUSER = USERS + "/getusertypeofuser";
    public static final String USERS_ADDUSER = USERS + "/adduser";
    public static final String USERS_UPDATEUSER = USERS + "/updateuser";
    public static final String USERS_CHANGEPASSWORD = USERS + "/changepassword";
    public static final String USERS_DELETEUSER = USERS + "/deleteuser";
    public static final String USERTYPES = "/usertypes";
    public static final String USERTYPES_GETUSERTYPE = USERTYPES + "/getusertype";
    public static final String USERTYPES_ADDUSERTYPE = USERTYPES + "/addusertype";
    public static final String USERTYPES_UPDATEUSERTYPE = USERTYPES + "/updateusertype";
    public static final String USERTYPES_DELETEUSERTYPE = USERTYPES + "/deleteusertype";
    public static final String SERVICES = "/services";
    public static final String SERVICES_GETSERVICE = SERVICES + "/getservice";
    public static final String SERVICES_GETMOSTUSEDSERVICESBYUSER = SERVICES + "/getmostusedservicesbyuser";
    public static final String SERVICES_GETDETAILEDSERVICES = SERVICES + "/getdetailedservices";
    public static final String SERVICES_GETDETAILEDSERVICESBYSERVICETYPE = SERVICES + "/getdetailedservicesbyservicetype";
    public static final String SERVICES_GETDETAILEDSERVICE = SERVICES + "/getdetailedservice";
    public static final String SERVICES_ADDSERVICE = SERVICES + "/addservice";
    public static final String SERVICES_UPDATESERVICE = SERVICES + "/updateservice";
    public static final String SERVICES_DELETESERVICE = SERVICES + "/deleteservice";
    public static final String SERVICETYPES = "/servicetypes";
    public static final String SERVICETYPES_GETSERVICETYPE = SERVICETYPES + "/getservicetype";
    public static final String SERVICETYPES_ADDSERVICETYPE = SERVICETYPES + "/addservicetype";
    public static final String SERVICETYPES_UPDATESERVICETYPE = SERVICETYPES + "/updateservicetype";
    public static final String SERVICETYPES_DELETESERVICETYPE = SERVICETYPES + "/deleteservicetype";
}
